const Constants = {
  FILMS_REQUEST: "FILMS_REQUEST",
  FILMS_SUCCESS: "FILMS_SUCCESS",
  FILMS_FAILURE: "FILMS_FAILURE",

  DELETE_FAVORITE: "DELETE_FAVORITE",
  ADD_FAVORITE: "ADD_FAVORITE",

  MOVIE_REQUEST: "MOVIE_REQUEST",
  MOVIE_SUCCESS: "MOVIE_SUCCESS",
  MOVIE_FAILURE: "MOVIE_FAILURE",

  GENRES_FETCH: "GENRES_FETCH",
  GENRES_REQUEST: "GENRES_REQUEST",
  GENRES_SUCCESS: "GENRES_SUCCESS",
  GENRES_FAILURE: "GENRES_FAILURE"
};
export default Constants;
