const Constants = {
  GET_FILMS_REQUEST: "GET_FILMS_REQUEST",
  GET_FILMS_SUCCESS: "GET_FILMS_SUCCESS",
  GET_FILMS_FAILURE: "GET_FILMS_FAILURE",
  DELETE_FAVORITE: "DELETE_FAVORITE",
  ADD_FAVORITE: "ADD_FAVORITE",
  GET_MOVIE_REQUEST: "GET_MOVIE_REQUEST",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  GET_MOVIE_FAILURE: "GET_MOVIE_FAILURE",
  SET_GENRES: "SET_GENRES"
};
export default Constants;
