const Constants = {
  GENRES_FETCH: "GENRES_FETCH",
  GENRES_REQUEST: "GENRES_REQUEST",
  GENRES_SUCCESS: "GENRES_SUCCESS",
  GENRES_FAILURE: "GENRES_FAILURE",

  FILMS_FETCH: "FILMS_FETCH",
  FILMS_REQUEST: "FILMS_REQUEST",
  FILMS_SUCCESS: "FILMS_SUCCESS",
  FILMS_FAILURE: "FILMS_FAILURE",

  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  ADD_FAVORITE: "ADD_FAVORITE",

  MOVIE_FETCH: "MOVIE_FETCH",
  MOVIE_REQUEST: "MOVIE_REQUEST",
  MOVIE_SUCCESS: "MOVIE_SUCCESS",
  MOVIE_FAILURE: "MOVIE_FAILURE"
};
export default Constants;
